spring:
  cloud:
    gcp:
      storage:
        credentials:
          locations: classpath: #{??? key?? ??}.json
  # ????? Spring Boot?? ???? {??? key?? ??}.json? ?? Storage? ???? @Autowired? ???? ???.
  # ??? ? ??? @Autowired? ?? ??? .json ?? ?? ???? ??? ?? ????.
        project-id: #{key ?? ?? ?? project_id ?}
        bucket: #{?? ??}


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/facegram?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        default_batch_fetch_size: 1000
        globally_quoted_identifiers: true
  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google ? ??? ???? ??.
            # localhost:8080/oauth2/authorization/google ? ??? ????.
            client-id: ??? ?? gcp ????? ???
            client-secret: ??? ?? gcp ????? ????
            redirectUri: http://localhost:8080/oauth2/callback/google
            scope: # ????? ???? ?????. ??? ?? ???? ??.
              - email
              - profile
  #OAuth2? ?? redirectUri? /login/oauth2/code/{provider} ???
      #ex) /login/oauth2/code/google
      #?? redirectUri? ??? ??? ?? ??? ??? ?? ??? ???? ??? application.yml? ???? ???
app:
  auth:
    token:
      secret-key: "GDSCSOLUTIONCHALLENGEBACKEND"
      refresh-cookie-key: "cookie"
  oauth2:
    authorizedRedirectUri: "/oauth2/redirect"


#  cloud:
#    gcp:
#      storage:
#        credentials:
#          location: classpath:




#spring:
#  datasource:
#    url: 'jdbc:h2:mem:facegram'
#    username: 'user'
#    password: ''
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#  h2:
#    console:
#      enabled: true
#      path: '/h2-console'